# Generated by Django 5.0 on 2023-12-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcatergory_subproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubProduct',
        ),
    ]
