# Generated by Django 5.0 on 2023-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_subproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryId', models.IntegerField()),
                ('subProductId', models.IntegerField()),
                ('subProductName', models.CharField(max_length=200)),
            ],
        ),
    ]
