# Generated by Django 5.0 on 2023-12-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='subcatergory',
            name='subCategoryId',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='subProductId',
        ),
        migrations.AlterField(
            model_name='subcatergory',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='subCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcatergory'),
        ),
    ]
